name: kittys_tavern
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For loading animations
  loading_animation_widget: ^1.2.0+2

  # A wonderful package that allows navigation without context
  get: ^4.6.5

  # Font support
  google_fonts: ^3.0.1

  # Fancy package that allows the coder to manipulate many aspects of a widget's display    
  themed: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/drinks/
    - assets/svg/
